// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkirgzbohyehpmaeekyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraXJnemJvaHllaHBtYWVla3luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTI0MDIsImV4cCI6MjA1NzU4ODQwMn0.vy2zVPQ0jl6IRK8ITBKVLOb1RCo_8Pq8ZIr4x5v-fkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);